#+TITLE: Dash

https://porque.life

http://127.0.0.1:8050/

https://hackrpi-spotify-query.herokuapp.com/

http://0.0.0.0:8000/

We are going to have a central website that we can point people towards. Within
the html for the website, there is an iframe link that calls to where the Dash
code is being run.

* Installation
Following: https://dash.plotly.com/installation
* Dash Deployment
- Following: https://dash.plotly.com/deployment
- Heroku Deployment: https://devcenter.heroku.com/articles/procfile


Setting up the virtual environment. Adds a list of dependencies and appends them
to [[file:requirements.txt]].
#+begin_src bash
virtualenv venv # creates a virtualenv called "venv"
source venv/bin/activate # uses the virtualenv
pip install dash
pip install plotly
pip install gunicorn
pip install pandas
pip install python-dotenv
pip freeze > requirements.txt
#+end_src

We next setup a Heroku app. This is what is going to host the dash code. Within
our html we will provide a link to the Heroku app.

#+begin_src bash
sudo ln -s /var/lib/snapd/snap /snap # for setting up --classic for snap
sudo snap install --classic heroku   # for installing heroku cli
heroku create # create a heroku app
heroku apps:rename hackrpi-spotify-query
heroku git:remote -a hackrpi-spotify-query
git push heroku main # push repo to heroku
#+end_src

We also need to add the right keys and tokens so that the Spotify API works proprely.

#+begin_src bash
heroku addons:create securekey --app hackrpi-spotify-query
#+end_src

* TODO List
** TODO Register a Domain Name
We need to decide on a name first. I am going to use the porque website in the
mean time.

https://www.tech.study/
* Interface
- Textbox for searching the artist
* List Comprehension for Multiple Input Boxes
#+begin_src python
types = ['Artist Name', "Year"]  # TODO add Year and what not later
input_types = ['text', 'number']

app.layout = html.Div(children = [
     html.H1(children='Spotify Data'),
     # html.Div(children='''Enter an Artist Name:'''),
    html.Div([
        dcc.Input(
            id = "my_{}".format([types[x]]),
            placeholder = "{}".format(types[x]),
            type = input_types[x],
            min = 2000, max= 2020, step = 1,
            minLength = 0, maxLength = 20, #num of characters inside input box
            autoComplete = 'on',
            disabled = False,  #disable input
            readOnly = False,  #make input box read only
            required = False,  #requires user to put something into input box  SET TRUE LATER
            size = "20"
            #style = {'',''}
            #className = ''
            #persistence = ''
            #persistence_type = ''
        ) for x in range(len(input_types))
    ]),
    html.Br(), #break (space between input and graph)
    dcc.Graph(id = "example-graph", figure = fig)
])

@app.callback( #call back links the data inputted with the graph  (Still working on this stuff below)
    [Output(component_id = "example-graph", component_property = 'figure')],
    [Input(component_id= "Year", component_property = "value")]
)

#function for the call back
def update_graph(compprop):
    print(compprop)
    print(type(compprop))
#+end_src
* Secret Keys
https://devcenter.heroku.com/articles/securekey#:~:text=Secure%20Key%20can%20be%20attached,%2Dclear%2D6489...&text=This%20can%20be%20confirmed%20using%20the%20heroku%20config%20command.
